spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://101.101.208.221:3306/db_live_god_life?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: live_god_life
    password: Onezo12#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true